version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes: # 開発効率上げ用
      - ./frontend/src:/app/src
    tty: true # TailwindCSSのホットリロード用
    environment: # TailwindCSSのホットリロード用
      - CHOKIDAR_USEPOLLING=true

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: