version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_DEFAULT_PRICE_ID=${STRIPE_DEFAULT_PRICE_ID}
      - APP_ENV=${APP_ENV}
      - APP_PORT=${APP_PORT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    volumes:
      - ./.env:/app/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_STRIPE_PRODUCT_ID=${VITE_STRIPE_PRODUCT_ID}
      - VITE_STRIPE_PRICE_ID=${VITE_STRIPE_PRICE_ID}
    volumes:
      - ./frontend/src:/app/src
      - ./.env:/app/.env
    # コンテナが終了しないようにするための最小限の設定
    tty: true
    stdin_open: true

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      # MongoDB認証有効化（セキュリティ強化）
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-changeme}
      MONGO_INITDB_DATABASE: juice_academy
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    command: ["--auth", "--bind_ip_all"]
    # セキュリティ: 本番環境では bind_ip を制限することを推奨

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
