version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
      - ./.env:/app/.env
    # コンテナが終了しないようにするための最小限の設定
    tty: true
    stdin_open: true

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      # MongoDB認証有効化（セキュリティ強化）
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-changeme}
      MONGO_INITDB_DATABASE: juice_academy
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    command: ["--auth", "--bind_ip_all"]
    # セキュリティ: 本番環境では bind_ip を制限することを推奨

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
